title: SEWS
author: Daniel Lockyer
url: https://sewsapp.com
description: Easy server monitoring
permalink: pretty
twitter:
  username: daniellockyer
author:
  name: Daniel Lockyer
  email: hi@daniellockyer.com
  twitter: DanielLockyer
defaults:
  -
    scope:
      path: ""
    values:
      layout: "base"

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
