title: SEWS
url: https://sewsapp.com
description: Easy server monitoring
permalink: pretty
twitter:
  username: daniellockyer
defaults:
  -
    scope:
      path: ""
    values:
      layout: "base"

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
